//! `cargo xtask mcp-docs`: render the agent tool catalog to docs/mcp.md
//! (spec §10.1). `--check` fails if the file is out of date.

use std::path::Path;

use anyhow::{Result, bail};
use serde_json::Value;

fn risk(r: agent_mcp::catalog::Risk) -> &'static str {
    match r {
        agent_mcp::catalog::Risk::ReadOnly => "Read-only — always allowed",
        agent_mcp::catalog::Risk::Reversible => "Reversible — allowed unless you ask to approve it",
        agent_mcp::catalog::Risk::External => "External — always needs your approval",
    }
}

fn type_of(schema: &Value) -> String {
    match schema["type"].as_str() {
        Some("array") => format!("array of {}", schema["items"]["type"].as_str().unwrap_or("value")),
        Some(t) => t.to_owned(),
        None => "value".to_owned(),
    }
}

pub fn render() -> String {
    let mut out = String::from(
        "# Agent tools (MCP)\n\n\
         The tools Kaluta gives an agent, through the `kaluta-mcp` server (spec §10). They are the \
         only way an agent can reach the mailbox: no shell, files or web. Every call passes the permission \
         engine and is recorded in Settings › Permissions › Activity.\n\n\
         Generated by `cargo xtask mcp-docs` from `crates/agent-mcp/src/catalog.rs`; do not edit by hand.\n",
    );
    for spec in agent_mcp::catalog() {
        out.push_str(&format!(
            "\n## `{}`\n\n{}\n\n**Risk:** {}\n",
            spec.name(),
            spec.description,
            risk(spec.tool.risk())
        ));
        arguments(&mut out, &spec.input_schema);
    }
    out.push_str(
        "\n# Mailbox mode: agents outside Kaluta\n\n\
         `kaluta-mcp --mailbox <address>` serves one agent mailbox to an agent that runs outside the app \
         (Claude Code, Codex, a script), whether or not Kaluta is open (spec §10.1). *Connect an Agent…* in \
         the mailbox's settings adds it to Claude Code or Codex. Only agent mailboxes are served, never the \
         user's own accounts. With Kaluta open every call goes through it, as the app's own agents' do: the \
         same permission engine, activity log and approvals. With Kaluta closed, reads open the mailbox's \
         store read-only, and a send is checked and recorded the same way, then queued: it goes out when \
         Kaluta next opens. A mailbox set to ask before each send cannot send while Kaluta is closed.\n",
    );
    for spec in agent_mcp::mailbox_catalog() {
        let risk = if spec.tool.read_only() {
            "Read-only — always allowed"
        } else {
            "External — sent freely or after your approval, as the mailbox's *When Agents Send* says"
        };
        out.push_str(&format!("\n## `{}` (mailbox mode)\n\n{}\n\n**Risk:** {risk}\n", spec.name(), spec.description));
        arguments(&mut out, &spec.input_schema);
    }
    out
}

fn arguments(out: &mut String, schema: &Value) {
    let props = schema["properties"].as_object().cloned().unwrap_or_default();
    if props.is_empty() {
        out.push_str("\nNo arguments.\n");
        return;
    }
    let required: Vec<&str> = schema["required"].as_array().into_iter().flatten().filter_map(Value::as_str).collect();
    out.push_str("\n| Argument | Type | Required | Notes |\n|---|---|---|---|\n");
    let mut names: Vec<&String> = props.keys().collect();
    names.sort_by_key(|n| (!required.contains(&n.as_str()), (*n).clone()));
    for name in names {
        let p = &props[name];
        let mut notes = p["description"].as_str().unwrap_or_default().replace('|', "\\|");
        if let Some(max) = p["maxItems"].as_u64() {
            notes = format!("{notes} At most {max}.").trim().to_owned();
        }
        if let Some(max) = p["maximum"].as_u64() {
            notes = format!("{notes} At most {max}.").trim().to_owned();
        }
        let req = if required.contains(&name.as_str()) { "yes" } else { "" };
        out.push_str(&format!("| `{name}` | {} | {req} | {notes} |\n", type_of(p)));
    }
}

pub fn run(root: &Path, check: bool) -> Result<()> {
    let path = root.join("docs/mcp.md");
    let rendered = render();
    if check {
        let current = std::fs::read_to_string(&path).unwrap_or_default();
        if current != rendered {
            bail!("docs/mcp.md is out of date: run `cargo xtask mcp-docs`");
        }
        println!("docs/mcp.md is up to date");
        return Ok(());
    }
    std::fs::write(&path, rendered)?;
    println!("wrote {}", path.display());
    Ok(())
}
